services:
  web:
    image: ghcr.io/j0ruge/louvorflow-web:${IMAGE_TAG:-staging}
    container_name: louvorflow-web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:80/index.html || exit 1']
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  default:
    name: ${NGINX_NETWORK_NAME}
    external: true
